var TokenTypes;
(function (TokenTypes) {
    TokenTypes[TokenTypes["WHITESPACE"] = 0] = "WHITESPACE";
    TokenTypes[TokenTypes["NEWLINE"] = 1] = "NEWLINE";
    TokenTypes[TokenTypes["HASH"] = 2] = "HASH";
    TokenTypes[TokenTypes["TEXT"] = 3] = "TEXT";
    TokenTypes[TokenTypes["DASH"] = 4] = "DASH";
    TokenTypes[TokenTypes["BLOCKQUOTE"] = 5] = "BLOCKQUOTE";
    TokenTypes[TokenTypes["OPEN_BRACKET"] = 6] = "OPEN_BRACKET";
    TokenTypes[TokenTypes["CLOSE_BRACKET"] = 7] = "CLOSE_BRACKET";
    TokenTypes[TokenTypes["OPEN_PAREN"] = 8] = "OPEN_PAREN";
    TokenTypes[TokenTypes["CLOSE_PAREN"] = 9] = "CLOSE_PAREN";
    TokenTypes[TokenTypes["ASTERISK"] = 10] = "ASTERISK";
    TokenTypes[TokenTypes["UNDERSCORE"] = 11] = "UNDERSCORE";
    TokenTypes[TokenTypes["BACKTICK"] = 12] = "BACKTICK";
    TokenTypes[TokenTypes["PIPE"] = 13] = "PIPE";
    TokenTypes[TokenTypes["COLON"] = 14] = "COLON";
    TokenTypes[TokenTypes["PERCENT"] = 15] = "PERCENT";
    TokenTypes[TokenTypes["OPEN_CURLY"] = 16] = "OPEN_CURLY";
    TokenTypes[TokenTypes["CLOSE_CURLY"] = 17] = "CLOSE_CURLY";
    TokenTypes[TokenTypes["EXCLAMATION"] = 18] = "EXCLAMATION";
    TokenTypes[TokenTypes["INDENT"] = 19] = "INDENT";
})(TokenTypes || (TokenTypes = {}));
export { TokenTypes };
